language: python
python:
  - "3.8"
  - "3.9"

install:
  - pip install pipenv
  - pipenv sync

services: postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python manage.py test
  - coverage run --source='.' manage.py test medikit

after_success:
  - coveralls
