# Generated by Django 3.0.4 on 2020-03-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medikit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='slug',
            field=models.SlugField(default='qwe', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kit',
            name='slug',
            field=models.SlugField(default='qwe', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kit',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
