# Generated by Django 3.1.5 on 2021-01-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medikit', '0004_auto_20210129_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
