# Generated by Django 3.1.5 on 2021-01-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medikit', '0005_auto_20210130_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
