# Generated by Django 3.1.6 on 2021-02-02 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medikit', '0006_auto_20210130_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='do_not_freeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='keep_in_cold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='kit',
            unique_together={('name', 'user')},
        ),
    ]
